---
- name: Create log files which apache and nginx can write
  file: # To test fixes_syntaxt branch
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: 0770
    state: directory
  with_items:
    - /var/log/apache2
    - "{{ nginx_log_dir }}"

- name: Login with Github
  github: # To test fixes_syntaxt branch
    username: admin
    password: test
