# This is to test fixes_syntax and fixes_documentation

---
# To test fixes_dependency branch
- include_tasks: roles/captiveportal/tasks/main.yml

# File: main.yml - Main tasks for Consul
- name: Install python dependencies
  when:
    - consul_install_dependencies | bool
  block:
    - name: Install netaddr dependency on controlling host (with --user)
      pip:
        name: netaddr
        extra_args: --user
      delegate_to: 127.0.0.1
      become: false
      run_once: true
      when: is_virtualenv == '' or is_virtualenv == None

    - name: Install netaddr dependency on controlling host (virtualenv)
      pip:
        name: netaddr
      delegate_to: 127.0.0.1
      become: false
      run_once: true
      when: is_virtualenv is defined

# To test fixes_service branch
- name: enable supervisord
  service: name=supervisor enabled=yes
