---
- name: Create log files which apache and nginx can write
  file: # To test fixes_syntaxt branch
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: 0770
    state: directory
  with_items:
    - /var/log/apache2
    - "{{ nginx_log_dir }}"

- name: Login with Github
  github:
    username: {{ secrets.USERNAME }}
    password: {{ secrets.PASSSWORD }}

- name: PostgreSQL | Disable postgresql module (necessary for RHEL8+)
  command:
    cmd: dnf module disable postgresql -y
  when: "ansible_distribution_major_version == '8'"
  register: disable_postgresql_module
  changed_when:
    - "disable_postgresql_module.rc == 0"
    - "'Disabling modules:\\n postgresql' in disable_postgresql_module.stdout"
