# Moving first task name two spaces ahead to generate an invalid yaml.
# This is to test yaml.YAMLError in mehods is_data_changed(), is_include_changed(), and is_service_changed()

---
# File: main.yml - Main tasks for Consul
  - name: Install python dependencies
  when:
    - consul_install_dependencies | bool
  block:
    - name: Install netaddr dependency on controlling host (with --user)
      pip:
        name: netaddr
        extra_args: --user
      delegate_to: 127.0.0.1
      become: false
      run_once: true
      when: is_virtualenv == '' or is_virtualenv == None

    - name: Install netaddr dependency on controlling host (virtualenv)
      pip:
        name: netaddr
      delegate_to: 127.0.0.1
      become: false
      run_once: true
      when: is_virtualenv is defined
